# Generated by Django 4.0.5 on 2022-08-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=100)),
                ('habitat', models.CharField(max_length=200)),
                ('diet', models.TextField(max_length=250)),
                ('price', models.IntegerField()),
                ('lifespan', models.CharField(max_length=100)),
            ],
        ),
    ]
